### ISSUE TITLE
Change in colour customisation behaviour

### ISSUE THREAD

**Issue by Midi-In** [SimpleMobileTools/Simple-App-Launcher#111]
With the last update of this, and several other Simple Mobile Tools applications, I noticed this particular note in the changelog:

- `Allow customizing app colors only after a Simple Thank You purchase`

What does that mean, is this a regression in usability and what's the reason behind such decision? Am I now supposed to pay for a feature in a suite of tools that I think were always supposed to be free? I'd like an honest explanation before I decide to update anything.
Thank you in advance

**Comment by tibbi** [comment]
Ye, you need to get https://play.google.com/store/apps/details?id=com.simplemobiletools.thankyou for color customization. It is a one time payment, meaning that once you purchase it, you will never have to pay for it again. Not even once you get a new device. Still more than a fair deal as the apps contain no ads and they take time and money to develop.

**Comment by Midi-In** [comment]
Thanks for the explanation. One more thing before closing the issue though - is the Thank You application from F-Droid any different than the one from Play Store?

**Comment by tibbi** [comment]
no, they are exactly the same
