### ISSUE TITLE
Forced package name

### ISSUE THREAD

**Issue by ybtag** [SimpleMobileTools/Simple-App-Launcher#118]
How could I easily modify the code to allow me to change the package name without getting a warning the first time the launcher starts? I would be glad to keep the name unchanged, but for technical reasons I need to change it (I need to fool my launcher into displaying it ;-} ). I see the issue is caused by implementing simplemobiletools commons.

**Comment by tibbi** [comment]
you cannot do that, the app is not supposed to be republished

**Comment by ybtag** [comment]
OK, funny thing for an open-source app

Yitzchok Bernstein


[cid:6e862976-c62b-45e4-ac97-8b16b6cf26c8]
________________________________
