### ISSUE TITLE
[Feature request] add Home screen style

### ISSUE THREAD

**Issue by Pantyhose-X** [SimpleMobileTools/Simple-App-Launcher#124]
All your apps will be shown on the Home screen.

**Describe the solution you'd like**
Show all apps on home screen

**Additional context**
![Screenshot_20210427-093745](https://user-images.githubusercontent.com/42504385/116172999-df004280-a75f-11eb-8048-50c44f2308ca.jpg)

**Comment by tibbi** [comment]
this isnt a real launcher, it cannot be set as the default for anything

**Comment by Pantyhose-X** [comment]
> this isnt a real launcher, it cannot be set as the default for anything

@tibbi  Simple no block device's cameras app ?
Simple block cameras ?
Protects you from apps that may be secretly recording you
