### ISSUE TITLE
Custom App Categories

### ISSUE THREAD

**Issue by lessgoo00** [SimpleMobileTools/Simple-App-Launcher#137]
Custom app categories would be a nice edition to this app. Having a games section, reading section etc. would make everything more organised

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
If this is implemented, I suggest that it be implemented as a tag system that the user decides how to present: as tabs or folders, etcetera. However, I am not certain that this amount of functionality is correct for simple software.

**Comment by tibbi** [comment]
that isnt on the roadmap in this app, it is too advanced
