### ISSUE TITLE
Placeholder Missing for translating

### ISSUE THREAD

**Issue by alanjacobmathew** [SimpleMobileTools/Simple-App-Launcher#166]
[https://hosted.weblate.org/translate/simple-mobile-tools/simple-app-launcher-metadata/en/](https://hosted.weblate.org/translate/simple-mobile-tools/simple-app-launcher-metadata/en/)

Content Missing on the 4th string for SimpleAppLauncher Metadata

**Comment by alanjacobmathew** [comment]
Same for https://hosted.weblate.org/translate/simple-mobile-tools/simple-calculator-metadata/en/

**Comment by tibbi** [comment]
you mean video.txt? The app has no video, the empty file has been added by fastlane. Just ignore it.
