### ISSUE TITLE
Deafaut Home app Launcher support (feature request)

### ISSUE THREAD

**Issue by rudrabhiseka** [SimpleMobileTools/Simple-App-Launcher#169]
Hello, I was looking for Simple home app launcher. I find Simple App Launcher as most simple one. Also it matches with theme and feel of other SimpleMobileTools apps on my mobile.

Please make it possible to set this app as Default home app launcher.

Pardon me, if i said something wrong. And thankyou so much to everyone here for making such simple elegant apps. Kudos!

**Comment by tibbi** [comment]
this app was not supposed to be a real laucher, that works in a whole different way. The proper app is being built already at https://github.com/SimpleMobileTools/Simple-Launcher.
