### ISSUE TITLE
Doubts regarding translating

### ISSUE THREAD

**Issue by alanjacobmathew** [SimpleMobileTools/Simple-App-Launcher#174]
https://hosted.weblate.org/translate/simple-mobile-tools/simple-app-launcher/ml/?q=#history

Hi, so looking back at the history of these translations, the reverting back to english for app names and app launcher name. Is it happening automatically due every time plugin updates, or there is no need for translating the App Name. 

Notes: Apps names are not literally translated, just transliterated.

**Comment by tibbi** [comment]
will keep an eye on it, I try not reverting translations
