### ISSUE TITLE
Error with android studio beta7

### ISSUE THREAD

**Issue by maxlinux2000** [SimpleMobileTools/Simple-App-Launcher#19]
Hi I can't build the proj due this error:

`Error:No signature of method: com.android.build.gradle.internal.scope.VariantScopeImpl.getGenerateRClassTask() is applicable for argument types: () values: []`

How I can fix it?

regards
MaX

**Comment by tibbi** [comment]
Hey, Im not sure, havent tried Android Studio 3 yet. Try googling the error I guess ;)
