### ISSUE TITLE
Please explain, in the Play Store description, the difference between "Simple App Launcher" and "Simple Launcher"

### ISSUE THREAD

**Issue by unforgettableid** [SimpleMobileTools/Simple-App-Launcher#198]
Hi,

I was looking in the Google Play store.  I see that you've created both "Simple App Launcher" and "Simple Launcher".

I have never used either app.  I looked in the Play Store descriptions of both apps, and I can't tell the difference between them.  What is the advantage of each app?  What is the disadvantage of each app?

It would be good if you could please edit the Play Store description of both apps, in order to tell us the advantage and disadvantage of each of the two apps.

Yes, users could just install both apps and figure out the difference themselves.  But it would save them time to be able to just read about the difference instead.

Thank you for creating all your apps, and for releasing them as open source!

**Comment by tibbi** [comment]
Hi, Simple App Launcher is just a testing app, a simple wrapper for your favorite app icons. Simple Launcher is the app most people are looking for, the one taking care of your home screen, widgets etc.

**Comment by unforgettableid** [comment]
> Simple App Launcher is just a testing app, a simple wrapper for your favorite app icons. Simple Launcher is the app most people are looking for, the one taking care of your home screen, widgets etc.

I appreciate your reply!

Could you please edit the Google Play store description of Simple App Launcher, to make it say the same thing you just told me?

**Comment by tibbi** [comment]
will consider it in the future, most people dont really read the descriptions anyway, they are there just for keywords

**Comment by unforgettableid** [comment]
> most people dont really read the descriptions anyway

Sounds plausible.  Still, some people do read the descriptions.  You can save them time by using the descriptions to tell them which simple launcher to install.
