### ISSUE TITLE
[Feature request] Change app names

### ISSUE THREAD

**Issue by kTyn9A9Kw3** [SimpleMobileTools/Simple-App-Launcher#2]
[app issue solved, other suggestion moved to general discussion]

**Comment by kTyn9A9Kw3** [comment]
What do you think about it? I mean, it's weird not in a negative way is just there's a lot of repetition of "Simple" words on the screen and since SMT are replacements for common utilities it would be more better looking if the apps were called simply by their functions, that way they could be translated too. Eg EN-IT: Simple Gallery -> Gallery -> Galleria
Also is not a problem to distinguish, with the typical orange icons we know they belong to the "Simple collection"

**Comment by tibbi** [comment]
In the app launcher you will be able to rename them, that should be good enough. I dont plan renaming them, there is a million "gallery" apps on the playstore. I have barely any time for working on them now, so I try focusing on the important things. Ill be able to work a bit more since autumn again.

**Comment by kTyn9A9Kw3** [comment]
The app name could remain the same what would change was the just the launcher name, I guess what is displayed on playstore is the app name not the launcher name. But looks like without intention I ended up giving a nice idea for the Simple App Launcher hehe

But with simple or not in the name the apps are still great specially the gallery. Thanks for the dedication :)

Just consider the suggestion for a future release more because of translations, imagine installing the app on a old person's phone or someone else who can't speak english very well or none at all plus tech and computers, it's a bit weird for that person all apps on native language except that one or two. Specially when it's a common utility on most mobile devices (Calendar, etc).

**Comment by tibbi** [comment]
I might consider it in the far future. Renaming in Simple App Launcher is already implemented for some time, that was a feature that makes sense there :)
