### ISSUE TITLE
App new release fails to install

### ISSUE THREAD

**Issue by surferjoeit** [SimpleMobileTools/Simple-App-Launcher#32]
Hello,
first of all thanks for this great app.
Unfortunately i have this problem with latest release (same with your Gallery app). If i try to update with F-Droid, it forces F-droid to close and don’t install.
In addition, i tried to manually download the apk file from github (Gallery app, for App launcher latest release there is no apk on github) and when i try to access the download folder, file manager suddenly closes. I have to manually remove the apk file by connecting device to PC and using PC file manager.
I had the same problem with other apps and it was related to a bug with android build tools:
https://issuetracker.google.com/issues/64434571
For other apps it has then been solved by changing build tools to 27.0.1.
I'm not a developer so i can't help you more than this.. sorry.
Android 5.0.2.

Thanks a lot

**Comment by trubitsyn** [comment]
Ref https://github.com/SimpleMobileTools/Simple-Gallery/commit/2edaa22b220976885c37ee1838a77d33da9e7916 for a similar issue

**Comment by trubitsyn** [comment]
@tibbi got all the apps patched. Sorry for so many pull requests. ;)

**Comment by tibbi** [comment]
@trubitsyn great, thanks.
@surferjoeit I will update all apps within a couple days on f-droid too, you will have to wait a bit. The App-launcher isnt really useful anyway, maybe you can try the gallery or so, it should work already :)

**Comment by tibbi** [comment]
aha, then just wait till then :D
