### ISSUE TITLE
Shared Theme is not Available when Activated from Other Apps in the Suite

### ISSUE THREAD

**Issue by thewizardstudio** [SimpleMobileTools/Simple-App-Launcher#37]
#### Expected Behavior
The Shared Theme is available in the Settings menu after having been created in other Apps in the Simple Mobile Tools Suite.

#### Actual Behavior
The Shared Theme is not available in the Settings menu after having been created in other Apps in the Simple Mobile Tools Suite.  Other apps in the Simple Mobile Tools Suite make the Shared Theme available correctly.

#### How to Reproduce
1. Launch Simple Calculator 3.1.1
2. Tap the 3 Horizontal Dots in Upper Right
3. Choose Settings -> Customize Colors -> Theme -> Dark Red
4. Tap Apply Colors to All Simple Apps -> OK
5. Launch Simpler App Launcher 3.1.1
6. Tap the 3 Horizontal Dots in Upper Right
7. Choose Settings -> Customize Colors -> Theme
8. Look for the 'Shared' option

---
    Device: Pixel 2 XL
    OS: Android 8.1.0
    App Version: 3.1.1
---

#### Recording of the Bug
![CustomColorsMissing.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517583815/kvjuoju6zihytj145bo2.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/shared-theme-is-not-available-when-activated-from-other-apps-in-the-suite">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by tibbi** [comment]
what version of Thank You do you have?
