### ISSUE TITLE
App names are always in English

### ISSUE THREAD

**Issue by tpimh** [SimpleMobileTools/Simple-App-Launcher#38]
If I change my locale, in Launcher3 all apps change their names to localized versions, but in in Simple-App-Launcher they are still in English.

**Comment by tibbi** [comment]
ye the app isnt translated in finish, if thats what you mean. If you want to translate it there is a guide at https://github.com/SimpleMobileTools/General-Discussion#how-do-i-add-a-new-file , let me know if you need help.

**Comment by tpimh** [comment]
No, that is not exactly what I mean. The app translation is great! I'll attach a screenshot to illustrate my point (first is Launcher3 in English, second is Simple-App-Launcher in English, third is Launcher3 in Russian (note translated app names), forth is Simple-App-Launcher in Russian that clearly shows the bug):
![example](https://user-images.githubusercontent.com/1071872/36470252-de975ff0-16f2-11e8-8b37-ec1bf91f5ca9.png)

**Comment by tibbi** [comment]
those app name strings are built into the app, Ill check if I can make it work like other launchers. Dont forget that it isnt a real launcher, just a casual app.
