### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by waqasanwar94** [SimpleMobileTools/Simple-App-Launcher#46]
Hello, @tibbi I want to contribute in "Simple App Launcher " so i designed a new logo for Simple App Launcher and it's free.

I hope you like it. If you like it, I will send you to pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.

if you want i will send you my design

**Comment by tibbi** [comment]
Hey, thanks but Im not looking for a new logo.
