### ISSUE TITLE
AWESOME LOGO DESIGN FREE FOR YOU 

### ISSUE THREAD

**Issue by abdulmalikkhan655** [SimpleMobileTools/Simple-App-Launcher#47]
Hello, @SimpleMobileToolsI want to contribute in "Simple-App-Launcher" so i  want to designed a new logo for "Simple-App-Launcher" and it's free.

I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.
if you want i will send you my design

contact me on facebook for fast delivary 
https://www.facebook.com/abdulmalikkhan655

**Comment by TacoTheDank** [comment]
I'm pretty sure this is a bot, he's posted this exact message in other projects I'm following
![screenshot_2018-05-15-08-04-53](https://user-images.githubusercontent.com/32376686/40055721-e7b0523a-5816-11e8-8667-5940ad240eb6.png)

not just in these two projects. He made one in Stringlate as well

**Comment by abdulmalikkhan655** [comment]
hehehe i am not bot dear i send manual sms for contribution for logo

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
This comment is response to “http://github.com/SimpleMobileTools/Simple-App-Launcher/issues/47#issuecomment-389145116 ”.

@abdulmalikkhan655, if you do actually post useful design that has already been created, it shall not only improve your portfolio, but shall demonstrate your commitment to assistance. Contradictorily, your current method of propogation of knowledge of your potential ability shall not be beneficial for anybody.
