### ISSUE TITLE
Allow associating with home button long-press action

### ISSUE THREAD

**Issue by Rikk** [SimpleMobileTools/Simple-App-Launcher#49]
Hi @tibbi this is a very interesting app. If you allow it to be associated with home button (my phone allows it to be long pressed only not slipped), I think this app could replace the outdated [Swipeup Utility](https://play.google.com/store/apps/details?id=com.AdrianCampos.swipeuputility). And if you could make it run as a overlay (look at the mentioned app) it would be even cooler.

**Comment by tibbi** [comment]
this is just a simple testing app, it is not meant to be used as a launcher. Some real launcher might come in the future.

**Comment by Rikk** [comment]
Ouch! I guess I should have explained better... Not make it into a Launcher, but allow associating with the long press action of the home button, which can open an app but not necessarily a launcher.

**Comment by tibbi** [comment]
aha ok I dont know that function, will take a look at it someday then

**Comment by Rikk** [comment]
Not sure, but maybe something related to search providers.

(Definitely, I think another new Launcher is a waste of development time — there are simply too many apps of this kind.)

**Comment by tibbi** [comment]
this wont be added in this app, maybe in Simple Launcher https://github.com/SimpleMobileTools/Simple-Launcher in the future
