### ISSUE TITLE
bug: when the Use English Language setting is changed, the Use English Language is not changed and is still in the same format as before

### ISSUE THREAD

**Issue by ramulah1** [SimpleMobileTools/Simple-App-Launcher#53]
#### Expected behavior
it should be, when I press the "option" feature and select the "settings" feature then change the "Use English Language" button, in the Simple App application the language will change, but the language remains unchanged.

#### Actual behavior
when I open the application and change the setting "Use English Language" in app simple app, the language does not change even though I have changed the icon.

#### How to reproduce
1. Install the application.

2. Open the app.

3. Click on icon (other options) in the app and click on the settings feature then select the "Use English Language" feature, then you will find the same problem as I experienced.
![IMG_20180601_183323.jpg](https://cdn.steemitimages.com/DQmXcZ1ySd15rK5n1j2FZ2aWTTCyGJX5KvJCgtdUPA1W8WC/IMG_20180601_183323.jpg)

![IMG_20180601_183408.jpg](https://cdn.steemitimages.com/DQmRS4qaZnjdozhcJYbTPz1ceFszDPDgqYWo7PJAMNm2eHV/IMG_20180601_183408.jpg)

----
- Device: Redmi Note 5A
- Operating system: 7.1.2 N2GHz
- (CPU: Octa-core Max 1.40 GHz, RAM: 3 GB)

Application Version: 
4.0.0

#### Recording Of The Bug

https://youtu.be/JazoLlM1808

**Comment by tibbi** [comment]
will be fixed in the next version
