### ISSUE TITLE
Bug: when changing feature in mode "avoid showing what's new at startup", but this feature does not work and startup view still same

### ISSUE THREAD

**Issue by ramulah1** [SimpleMobileTools/Simple-App-Launcher#54]
#### Expected behavior
when I select the "avoid showing what's new on startup" feature on the "Setings" icon, the startup view will change, but the startup view does not change at all and still in the same view.

#### Actual behavior
when I change the display "avoid showing what's new on startup" in the simple app Launcher, the startup view does not change even though I've changed the settings icon.

#### How to reproduce
1. Install app.

2. Open the app.

3. Click on icon (other options) in the app.
![IMG_20180602_010605.jpg](https://cdn.steemitimages.com/DQmNX94B9eZFnLebWmfwBLJ8YzCynZPFJ5Xy8CikcFqYr8S/IMG_20180602_010605.jpg)

4. click on the settings feature then select the "avoid showing what's on new on startup" feature, then you will find the same problem as I experienced.
![IMG_20180602_010704.jpg](https://cdn.steemitimages.com/DQmf4SWNhssDzZomzNZ2DUpLUgncapThQbczpLV8H57XGYJ/IMG_20180602_010704.jpg)
 And
![IMG_20180602_010739.jpg](https://cdn.steemitimages.com/DQmfBKxn8PmAvoHjjtg1HE4RyEP8krcGVfS2s1AmnZmy3a9/IMG_20180602_010739.jpg)
----
- Device: Redmi Note 5A
- Operating system: 7.1.2 N2GHz
- (CPU: Octa-core Max 1.40 GHz, RAM: 3 GB)

Application Version: 
4.0.0

#### Recording Of The Bug

https://youtu.be/bkhby-CLGNI

**Comment by tibbi** [comment]
that toggle is about a dialog listing new app features, it works fine

**Comment by ramulah1** [comment]
hi mr @tibbi . I'm sorry I changed the language
