### ISSUE TITLE
problem in build

### ISSUE THREAD

**Issue by CoderoidAcademy** [SimpleMobileTools/Simple-App-Launcher#67]
sync gradle is fine
but when i wan to build APK show this error

Error: Program type already present: android.support.v4.app.INotificationSideChannel

why?

**Comment by tibbi** [comment]
in android studio try doing Refactor -> Migrate to AndroidX

**Comment by tibbi** [comment]
retry with 5.0.3, there was no gradle.properties file uploaded before
