### ISSUE TITLE
FR: Add choice of store

### ISSUE THREAD

**Issue by claudiusraphaelpaeth** [SimpleMobileTools/Simple-App-Launcher#82]
I just installed SimpleAppLauncher from F-Droid. When accessing e.g. the SimpleCamera from it it opens up the Google PlayStore.

I checked Settings for an option to use F-Droid for missing Apps without the necessity to make F-Droid the System Default.

Would that be possible: Offering a choice which Store to use for missing Apps?

I am interested in it in general, even if SimpleMobileTools don't like to offer it, let me ask for a hint what to research and study to enable such a feature on a per-app basis.

Thanks.

**Comment by tibbi** [comment]
it already works like that
