### ISSUE TITLE
Please add option to backup launcher settings

### ISSUE THREAD

**Issue by rustforfuture** [SimpleMobileTools/Simple-App-Launcher#86]
Hello

Please add option to backup launcher settings, this includes apps that added to it and also qill be great to have other settings like their sort, folder and ...  (if you added those options also)

Thank you very much.
Best regards.

**Comment by tibbi** [comment]
that isnt on the roadmap, some more advanced features will be added in Simple Launcher at https://github.com/SimpleMobileTools/Simple-Launcher
